### ISSUE TITLE
Scripts for Back-translation?

### ISSUE THREAD

**Issue by ashim95** [facebookresearch/flores#1]
Hi, 
Thanks for releasing the code and datasets. 

Are you going to release the scripts you used for back-translation, and in general a single script to run (train) the system in one go?

Thanks again,
Ashim

**Comment by myleott** [comment]
Yes, we plan to release this soon.

**Comment by myleott** [comment]
Yes, we plan to release scripts for back-translation soon.

**Comment by ashim95** [comment]
Hi @myleott , 
Any updates on when you plan to release the scripts for back-translation?

Thanks,

**Comment by vishrav** [comment]
We have started releasing the back-translation scripts. Please refer to the readme.
