### ISSUE TITLE
Can't Decompress ”commoncrawl.deduped.en.xz“.

### ISSUE THREAD

**Issue by zdou0830** [facebookresearch/flores#10]
Hi, I'm having trouble decompressing ”commoncrawl.deduped.en.xz“. 

> unxz: commoncrawl.deduped.en.xz: Unexpected end of input

I can decompress other files. Is there anything wrong with the file?

_Originally posted by @zdou0830 in https://github.com/facebookresearch/flores/issues/5#issuecomment-507089496_

**Comment by jmp84** [comment]
@zdou0830, I can repro:
```
  curl http://data.statmt.org/wmt19/parallel-corpus-filtering/commoncrawl.deduped.en.xz > commoncrawl.deduped.en.xz
  unxz commoncrawl.deduped.en.xz
unxz: commoncrawl.deduped.en.xz: Unexpected end of input
```

I suggest emailing wmt-tasks@googlegroups.com about this issue.
I'm going to close since the data is not in this repository.
