### ISSUE TITLE
Pashto Language does not have test set

### ISSUE THREAD

**Issue by ShaidaMuhammad** [facebookresearch/flores#19]
After downloading the dataset from https://raw.githubusercontent.com/facebookresearch/flores/master/data/flores_test_sets.tgz, I do not see any Testset for **en-ps** language pairs. I see only two sets 
1). wikipedia.dev.ps-en 
2). wikipedia.devtest.ps-en

**Comment by vishrav** [comment]
Shaida we released a new dataset for 101 languages. Please refer to the new download link.
