### ISSUE TITLE
Error encountered when running prepare-neen.sh

### ISSUE THREAD

**Issue by zdou0830** [facebookresearch/flores#2]
IOError: [Errno 2] No such file or directory: './data/all-clean-ne/bible_dup.en-ne.ne'
![image](https://user-images.githubusercontent.com/43542692/52322624-d917be80-29a7-11e9-8870-e0fcb55c68fa.png)

**Comment by jmp84** [comment]
I can verify this issue. We will upload a new version as soon as possible.

**Comment by jmp84** [comment]
@zdou0830, this should be fixed now, please let us know if you still face this issue.
