### ISSUE TITLE
Broken download link

### ISSUE THREAD

**Issue by berlino** [facebookresearch/flores#20]
The link "http://www.casmacat.eu/corpus/global-voices/globalvoices.ne-en.xliff.gz" from download_data.sh is broken for at least one week. 

I'm wondering if there is any other way I can download it, or if someone is willing to share it with me.

Thanks!

**Comment by putheakhem** [comment]
@berlino I haven't tested the current code. However I do merge by my own with the  issues #17  then everything is works fine.

**Comment by JunjieHu** [comment]
@berlino I end up downloading the file manually from this [link](https://opus.nlpl.eu/GlobalVoices.php)
