### ISSUE TITLE
bad gateway for data downloading

### ISSUE THREAD

**Issue by amiktt** [facebookresearch/flores#3]
Error Bad Gateway 502 when trying to download dataset in running download-data.sh 
http://www.cfilt.iitb.ac.in/iitb_parallel/iitb_corpus_download/parallel.tgz

**Comment by vishrav** [comment]
Thanks for reporting this. I have sent an email to the contributors of this dataset to fix the link. I will update you once the issue is resolved.

**Comment by vishrav** [comment]
The server hosting the data went down. It should be up and running in a day (ETA from the contributors of this dataset).
