### ISSUE TITLE
Scripts to Scrape Data?

### ISSUE THREAD

**Issue by neubig** [facebookresearch/flores#6]
Thanks again for releasing this dataset, it's super-helpful!

We are very interested in using this on the Sinhalese and Nepalese data itself, but also want to test out methods for cross-lingual transfer learning, where we learn from higher-resourced languages to improve accuracy on the Sinhalese and Nepalese datasets. Would it be possible to get scripts or instructions on how to scrape the monolingual and comparable data reported in the paper, so we can scrape data for other similar language pairs?

**Comment by vishrav** [comment]
Hi Graham,

The monolingual wikipedia data can be downloaded from the shared task website http://www.statmt.org/wmt19/parallel-corpus-filtering.html. 

For monolingual commoncrawl data you can refer to the instructions mentioned in the attached file
[monolingual_cc.txt](https://github.com/facebookresearch/flores/files/3035956/monolingual_cc.txt)

We are also in process of releasing the cleaned monolingual dataset and I will update you once it's done.

**Comment by neubig** [comment]
Thanks for the fast reply @vishrav! Actually my question was not about how to download the existing data, but rather if we could get scripts so that we could create a similar dataset from the common crawl for other languages. For example, we would like to create a dataset for Hindi-English, as it would be similar to the Sinhala-English dataset.

**Comment by vishrav** [comment]
Sure so for preparing the commoncrawl dataset for other languages you can refer to "monlingual_cc.txt" (attached in the previous comment)

**Comment by neubig** [comment]
Ahh, I see! Just in case it isn't clear to others reading the thread, going to http://data.statmt.org/ngrams/raw/ to find the files for the appropriate language, and replacing the ``LINKS`` variable in the file above with the links.

For the "cleaned monolingual" dataset that you referred to above, is that what is referred to as the  "comparable" dataset in the paper? If so, that'd be great! Looking forward to the scripts.

**Comment by vishrav** [comment]
"comparable" dataset in the paper is the noisy web crawled data coming from paracrawl http://www.statmt.org/wmt19/parallel-corpus-filtering.html
